### ISSUE TITLE
字幕组招收打轴、压制、校对（日英），知识类烤肉/galgame汉化向。福利待遇：每日三百张以上高质量S图

### ISSUE THREAD

**Issue by zabiy1** [interesting-1024/end#231]

**Comment by mkcoldwolf** [comment]
草 汉化组都来了

**Comment by duiweiya** [comment]
300张不够，500张可以吗？

**Comment by lyscf** [comment]
300张不够，500张可以吗？

**Comment by zabiy1** [comment]
> 300张不够，500张可以吗？

**Comment by zabiy1** [comment]
> 300张不够，500张可以吗？

我们严格遵守劳动法
(一)安排劳动者延长工作时间的，支付不低于工资的百分之一百五十的工资报酬;
(二)休息日安排劳动者工作又不能安排补休的，支付不低于工资的百分之二百的工资报酬;
(三)法定休假日安排劳动者工作的，支付不低于工资的百分之三百的工资报酬。
节假日工作我们会付法定倍率的数量

**Comment by Yoooooory** [comment]
能先发些确认下质量吗

**Comment by LuoMuyu** [comment]
先来点看看质量
