### ISSUE TITLE
真的有参数能进end.php这段判断吗

### ISSUE THREAD

**Issue by festoney8** [interesting-1024/end#236]
https://github.com/interesting-1024/end/blob/main/end.php#L7-L10

真的有参数能进这段判断吗，我看又要求是数又要不是数...

```
$str = intval($_GET['id']);
$reg = preg_match('/\d/is', $_GET['id']);

if(!is_numeric($_GET['id']) and $reg !== 1 and $str === 1)
```

不懂php，求问这段代码是要求 “不是数字 且 不满足正则 且 值为1” 吗？

**Comment by PHINEXLISY** [comment]
1代表true

**Comment by UnknownMistyRain** [comment]
有 非空数组

**Comment by SpriteOvO** [comment]
https://www.runoob.com/php/php-intval-function.html

> 成功时返回 var 的 integer 值，失败时返回 0。 空的 array 返回 0，非空的 array 返回 1。

**Comment by Howard20181** [comment]
```id[]&url=.flag.txt```

**Comment by ZanyRain** [comment]
可以的，可以先搜一下，我不会PHP就是连蒙带搜的过了

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by festoney8** [comment]
> `id[]&url=.flag.txt`

我试了用end.php自建，这个参数报给我
Warning: preg_match() expects parameter 2 to be string, array given

**Comment by snwf** [comment]
id[]=1&url=php://input
