### ISSUE TITLE
有一张图可能有其他提示

### ISSUE THREAD

**Issue by Howard20181** [interesting-1024/end#245]
![image](https://activity.hdslb.com/blackboard/activity28580/assets/main/kv.ae012f4b77223c1fd205b91df75e98a9.png)
这张图提示了存在XSS漏洞 
#202

**Comment by paulzzh** [comment]
这张图甚至误导我去用 api/images?file= 去搞/etc/passwd来弄第三题的帐号密码、、、

**Comment by sparrowhe** [comment]
> 这张图甚至误导我去用 api/images?file= 去搞/etc/passwd来弄第三题的帐号密码、、、

你们这是什么图啊 你们这个图害人不浅

**Comment by ZanyRain** [comment]
> 这张图甚至误导我去用 api/images?file= 去搞/etc/passwd来弄第三题的帐号密码、、、

同款被坑，不过那个C代码，如果 first_msg 为空，那么last_msg也为空，会不会预示着什么

有点抓狂

**Comment by Howard20181** [comment]
> > 这张图甚至误导我去用 api/images?file= 去搞/etc/passwd来弄第三题的帐号密码、、、
> 
> 同款被坑，不过那个C代码，如果 first_msg 为空，那么last_msg也为空，会不会预示着什么
> 
> 有点抓狂

想到 ```single.php``` 没有id这个参数为空，那有这个参数但是什么都不写就不空了

**Comment by sparrowhe** [comment]
> > 这张图甚至误导我去用 api/images?file= 去搞/etc/passwd来弄第三题的帐号密码、、、
> 
> 同款被坑，不过那个C代码，如果 first_msg 为空，那么last_msg也为空，会不会预示着什么
> 
> 有点抓狂

?哪个C代码 那张图吗

**Comment by Howard20181** [comment]
> > > 这张图甚至误导我去用 api/images?file= 去搞/etc/passwd来弄第三题的帐号密码、、、
> > 
> > 
> > 同款被坑，不过那个C代码，如果 first_msg 为空，那么last_msg也为空，会不会预示着什么
> > 有点抓狂
> 
> ?哪个C代码 那张图吗

就这个话题提到的这张

**Comment by sparrowhe** [comment]
> > > > 这张图甚至误导我去用 api/images?file= 去搞/etc/passwd来弄第三题的帐号密码、、、
> > > 
> > > 
> > > 同款被坑，不过那个C代码，如果 first_msg 为空，那么last_msg也为空，会不会预示着什么
> > > 有点抓狂
> > 
> > 
> > ?哪个C代码 那张图吗
> 
> 就这个话题提到的这张

魔怔了

**Comment by ZanyRain** [comment]
他那个都是反代，可能有内网实例或者docker容器，所以我觉得任意文件读取应该都是写死的，本身并不存在这种漏洞。
所以我在想 single.php是不是php也不一定，这完全能伪装一下。

________________________________
发件人: Howard20181 <notifications@github.com>
发送时间: 2020年10月25日星期日 下午5:27
收件人: interesting-1024/end
抄送: ZanyRain; Comment
主题: Re: [interesting-1024/end] 有一张图可能有其他提示 (#245)


这张图甚至误导我去用 api/images?file= 去搞/etc/passwd来弄第三题的帐号密码、、、

同款被坑，不过那个C代码，如果 first_msg 为空，那么last_msg也为空，会不会预示着什么

有点抓狂

想到 single.php 没有id这个参数为空，那有这个参数但是什么都不写就不空了

―

**Comment by Howard20181** [comment]
> > 这张图甚至误导我去用 api/images?file= 去搞/etc/passwd来弄第三题的帐号密码、、、
> 
> 同款被坑，不过那个C代码，如果 first_msg 为空，那么last_msg也为空，会不会预示着什么
> 
> 有点抓狂

发现这段是ijkplayer的代码片段
https://github.com/search?q=q-%3Efirst_msg&type=code
