### ISSUE TITLE
Flag6

### ISSUE THREAD

**Issue by BaseCert** [interesting-1024/end#286]
It seems inappropriate to do so. I'd better delete it.

**Comment by mkcoldwolf** [comment]
??????????

**Comment by Hashida-Itaru-19910519** [comment]
直接放出来就很没意思，至少让白嫖党自己手动跑跑脚本吧

**Comment by AveryKL-1213** [comment]
啊这

**Comment by BaseCert** [comment]
> 
> 
> ??????????

This is the flag of question 6.
I tried it just now, and it seems to be right.

**Comment by mkcoldwolf** [comment]
> > ??????????
> 
> This is the flag of question 6.
> I tried it just now, and it seems to be right.

U shouldn't post it out, as the floor 3 said, there is already python code solution, its not meaningful to just public the answer, at least u should let those players run the code themselvces
