### ISSUE TITLE
路过刘明，圈外人退了

### ISSUE THREAD

**Issue by festoney8** [interesting-1024/end#68]
![Snipaste_2020-10-24_17-52-56](https://user-images.githubusercontent.com/36254268/97078890-20cdf600-1622-11eb-83fb-d89e6cfb72c7.png)

为什么周六自己给自己加班，喝酒吃饭去

ps: 排行榜上id怎么有几个眼熟的

**Comment by tnicid** [comment]
我只认识mcfx和mathlover（
