### ISSUE TITLE
意思是会PHP的才算程序员？真有你的

### ISSUE THREAD

**Issue by yihleego** [interesting-1024/end#73]
![1JK}GOE20DI( D4)1UUO@0S](https://user-images.githubusercontent.com/21337386/97078882-ff6d0a00-1621-11eb-8bda-f2777856dfc6.gif)

**Comment by polichan** [comment]
爱了爱了

**Comment by 412845222** [comment]
爱了爱了

**Comment by teble** [comment]
ctf挖php漏洞不是正常操作(

**Comment by chenyuwulu** [comment]
现在b站不是老早换vue react搭配golang了么

**Comment by tingxiaoxi** [comment]
咋了。。。

**Comment by goodboy95** [comment]
php漏洞多，所以ctf搞代码审计肯定是php

**Comment by AFKL-CUIT** [comment]
不是...打CTF不得懂点php的黑魔法？（

**Comment by SaigyoujiYuyuko233** [comment]
这都可以引战?

**Comment by happygong** [comment]
这不还有JS嘛（狗头保命）

**Comment by sirodeneko** [comment]
hhh是因为php漏洞多(狗头）
